name: HonestFast
options:
  bundleIdPrefix: com.loopspur
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "16.0"
  generateEmptyDirectories: true

settings:
  base:
    SWIFT_VERSION: "5.9"
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: 1

targets:
  HonestFast:
    type: application
    platform: iOS
    sources:
      - HonestFast
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.loopspur.honestfast
        INFOPLIST_VALUES: >-
          UILaunchScreen_Generation=YES
          UIApplicationSceneManifest_Generation=YES
          CFBundleDisplayName=Honest Fast
          CFBundleName=Honest Fast
          UIBackgroundModes=
        SUPPORTS_MACCATALYST: false
        TARGETED_DEVICE_FAMILY: 1
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        SWIFT_EMIT_LOC_STRINGS: "YES"
        DEVELOPMENT_TEAM: ""
