name: HonestFast
options:
  bundleIdPrefix: com.loopspur
  deploymentTarget:
    iOS: "17.0"
    watchOS: "10.0"
  xcodeVersion: "16.0"
  generateEmptyDirectories: true

settings:
  base:
    SWIFT_VERSION: "5.9"
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: 1

targets:
  HonestFast:
    type: application
    platform: iOS
    sources:
      - HonestFast
    entitlements:
      path: HonestFast/HonestFast.entitlements
    dependencies:
      - target: HonestFastWidget
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.loopspur.honestfast
        INFOPLIST_VALUES: >-
          UILaunchScreen_Generation=YES
          UIApplicationSceneManifest_Generation=YES
          CFBundleDisplayName=Honest Fast
          CFBundleName=Honest Fast
          UIBackgroundModes=
        SUPPORTS_MACCATALYST: false
        TARGETED_DEVICE_FAMILY: 1
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        SWIFT_EMIT_LOC_STRINGS: "YES"
        DEVELOPMENT_TEAM: ""
        CODE_SIGN_ENTITLEMENTS: HonestFast/HonestFast.entitlements

  HonestFastWatch:
    type: application
    platform: watchOS
    sources:
      - HonestFastWatch
    entitlements:
      path: HonestFastWatch/HonestFastWatch.entitlements
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.loopspur.honestfast.watch
        INFOPLIST_VALUES: >-
          CFBundleDisplayName=Honest Fast
          WKCompanionAppBundleIdentifier=com.loopspur.honestfast
        DEVELOPMENT_TEAM: ""
        CODE_SIGN_ENTITLEMENTS: HonestFastWatch/HonestFastWatch.entitlements

  HonestFastWidget:
    type: app-extension
    platform: iOS
    sources:
      - HonestFastWidget
    entitlements:
      path: HonestFastWidget/HonestFastWidget.entitlements
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.loopspur.honestfast.widget
        INFOPLIST_VALUES: >-
          CFBundleDisplayName=Honest Fast Widget
          NSExtension_NSExtensionPointIdentifier=com.apple.widgetkit-extension
        DEVELOPMENT_TEAM: ""
        CODE_SIGN_ENTITLEMENTS: HonestFastWidget/HonestFastWidget.entitlements
